# Generated by Django 4.1.2 on 2024-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0002_assetclass_created_on_assetclass_deleted_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geography",
            name="type",
            field=models.CharField(default="country", max_length=100),
            preserve_default=False,
        ),
    ]
