# Generated by Django 4.1.2 on 2023-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0002_alter_user_company_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
