# Generated by Django 4.1.2 on 2024-02-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0003_geography_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="geography",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meltexapp.geography"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="sub_asset_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="meltexapp.subassetclass",
            ),
        ),
        migrations.AlterField(
            model_name="registerinterest",
            name="buyer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registerinterest",
            name="seller_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
