# Generated by Django 4.1.2 on 2023-10-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0003_listing_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="asset_class_name",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="sub_asset_class_name",
        ),
        migrations.AddField(
            model_name="listing",
            name="asset_class",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="meltexapp.assetclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sub_asset_class",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="meltexapp.subassetclass",
            ),
            preserve_default=False,
        ),
    ]
