# Generated by Django 4.1.2 on 2024-02-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0004_alter_listing_geography_alter_listing_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geography",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="geography",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="meltexapp.geography",
            ),
        ),
    ]
