# Generated by Django 4.1.2 on 2023-10-20 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0004_remove_listing_asset_class_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="asset_class",
        ),
    ]
