# Generated by Django 4.1.2 on 2023-10-24 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0005_remove_listing_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 24, 10, 35, 37, 519475)
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 24, 10, 35, 37, 519484)
            ),
        ),
    ]
