# Generated by Django 4.1.2 on 2023-10-26 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0006_listing_created_on_listing_deleted_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 15, 47, 14, 594327)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 15, 47, 14, 594335)
            ),
        ),
    ]
