# Generated by Django 4.1.2 on 2024-02-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0006_remove_registerinterest_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerinterest",
            name="listing",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="meltexapp.listing",
            ),
            preserve_default=False,
        ),
    ]
