# Generated by Django 4.1.2 on 2024-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0007_registerinterest_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="geography",
            name="key",
            field=models.CharField(default="c", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
