# Generated by Django 4.1.2 on 2024-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0007_registerinterest_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="registerinterest",
            unique_together={("buyer_user", "listing")},
        ),
    ]
