# Generated by Django 4.1.2 on 2024-03-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meltexapp", "0008_message_read_alter_registerinterest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(default="test job title", max_length=50),
            preserve_default=False,
        ),
    ]
